"""Build the README results block (and results/summary.json) from result files.

Every number in the generated block is read from a CSV/JSON that another script
wrote, or recomputed from the cached raw data here. Nothing is typed by hand.

Run from the repo root:  python -m scripts.build_summary
It rewrites the text between the RESULTS markers in README.md.
"""
from __future__ import annotations

import json
import re

import pandas as pd

from src.data.statsbomb import load_all_events, load_all_matches
from src.features.shots import exclusion_counts
from src.utils.config import ROOT, load_config, resolve

START, END = "<!-- RESULTS:START (generated by scripts/build_summary.py; do not edit) -->", \
    "<!-- RESULTS:END -->"


def md_table(df: pd.DataFrame) -> str:
    """Minimal GitHub-markdown table (avoids needing the `tabulate` package)."""
    cols = [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for row in df.itertuples(index=False):
        lines.append("| " + " | ".join("" if pd.isna(v) else str(v) for v in row) + " |")
    return "\n".join(lines)


def mean_of(cell: str) -> float:
    """'0.2580 +/- 0.0231' -> 0.2580"""
    return float(cell.split("+/-")[0])


def dataset_section(res_dir) -> tuple[str, dict]:
    matches = load_all_matches()
    events = load_all_events(matches)
    ex = exclusion_counts(events)
    shots = pd.read_csv(resolve(load_config()["paths"]["processed"]) / "shots.csv")
    s = {"matches": int(len(matches)), "events": int(len(events)), **ex,
         "model_goals": int(shots["is_goal"].sum()),
         "model_goal_rate": round(float(shots["is_goal"].mean()), 4),
         "model_matches": int(shots["match_id"].nunique())}
    names = [c["name"] for c in load_config()["statsbomb"]["competitions"]]
    text = (f"**Data:** {', '.join(names)}: {s['matches']} matches, {s['events']:,} events, "
            f"{s['all_shots']:,} shots.\n\n"
            f"**xG modelling set:** {s['modelled_shots']:,} shots from {s['model_matches']} matches "
            f"({s['model_goals']} goals, goal rate {s['model_goal_rate']:.2%}). "
            f"Excluded: {s['excluded_penalties']} in-match penalties and "
            f"{s['excluded_shootout_kicks']} shoot-out kicks.")
    return text, s


def xg_section(res_dir) -> tuple[str, dict]:
    main = pd.read_csv(res_dir / "xg_results.csv")
    pooled = pd.read_csv(res_dir / "xg_results_pooled_oof.csv", index_col=0).reset_index()
    pooled = pooled.rename(columns={"index": "model"})
    paired = pd.read_csv(res_dir / "xg_results_paired_differences.csv")
    ff = pd.read_csv(res_dir / "xg_results_freeze_frame.csv")
    loco = pd.read_csv(res_dir / "xg_results_leave_one_tournament_out.csv")
    base = main[~main["model"].str.startswith("statsbomb")]
    best = base.loc[base["log_loss"].map(mean_of).idxmin()]
    sb = main[main["model"].str.startswith("statsbomb")].iloc[0]
    lr_ff = ff[ff["model"] == "logreg_all"].iloc[0]
    sb_pair = paired[paired["model"].str.startswith("statsbomb")].iloc[0]
    facts = {"best_model": best["model"], "best_log_loss": mean_of(best["log_loss"]),
             "statsbomb_log_loss": mean_of(sb["log_loss"]),
             "logreg_all_freeze_frame_log_loss": mean_of(lr_ff["log_loss"]),
             "statsbomb_better_in_folds": int(sb_pair["folds_better_than_logreg_all"])}
    close = paired[paired["model"].isin(["lightgbm", "mlp"])]
    tied = bool((close["mean_diff_vs_logreg_all"].abs() < close["std_diff"]).all())
    tie_text = ("the three full models (logistic regression, LightGBM, MLP) differ by less "
                "than the paired fold-to-fold spread, so they are statistically tied"
                if tied else "the full models differ by more than the paired fold-to-fold "
                "spread (see the paired table)")
    sb_text = ("It is a benchmark that this project does not beat."
               if facts["statsbomb_log_loss"] < facts["best_log_loss"]
               else "This project's best model scores better than the StatsBomb benchmark on "
                    "this metric; treat that with suspicion until investigated.")
    text = [
        "#### Model comparison (5-fold CV grouped by match, mean ± std across folds)\n",
        md_table(main.drop(columns="features")),
        "\n#### Pooled out-of-fold metrics (every shot scored by a model that never saw its match)\n",
        md_table(pooled),
        "\n`ece_noise_floor` = the ECE expected from sampling noise alone if the predictions were "
        "exactly right (simulated from each model's own probabilities).\n",
        "\n#### Paired per-fold log-loss difference vs `logreg_all` (positive = worse)\n",
        md_table(paired),
        "\n#### With freeze-frame features (defenders in the shot cone, goalkeeper position)\n",
        md_table(ff.drop(columns="features")),
        "\n#### Leave one tournament out\n",
        md_table(loco.drop(columns="features")),
        "\n#### Key findings (generated from the tables above)\n",
        f"- Lowest mean CV log loss: **{facts['best_model']}** ({facts['best_log_loss']:.4f}); "
        f"{tie_text}.",
        f"- StatsBomb's own xG scores {facts['statsbomb_log_loss']:.4f} log loss and is better than "
        f"`logreg_all` in {facts['statsbomb_better_in_folds']} of 5 folds. {sb_text}",
        f"- Adding freeze-frame features moves `logreg_all` from {facts['best_log_loss']:.4f} to "
        f"{facts['logreg_all_freeze_frame_log_loss']:.4f}.",
    ]
    return "\n".join(text), facts


def tracking_section(res_dir) -> str:
    ph = res_dir / "phase4"
    rows, rel_rows = [], []
    for g in (1, 2):
        q = json.loads((ph / f"quality_game{g}.json").read_text())
        for team in ("home", "away"):
            t = q[team]
            d = q["despike"][team]
            rows.append({
                "game": g, "team": team, "frames": q["frames"], "fps": q["fps"],
                "squad_columns": t["squad_columns"],
                "raw_steps_over_12_m/s": t["raw_speed_over_12ms"],
                "raw_max_step_speed_m/s": t["raw_speed_max_ms"],
                "points_blanked": d["glitch_points_flagged"] + d["impossible_step_points_blanked"],
                "steps_over_12_m/s_after_cleaning": t["raw_speed_over_12ms_after_despike"],
                "ball_missing_frames": t["ball_nan_frames"],
                "periods_flipped": str(q["periods_flipped_to_make_home_attack_right"])})
        for variant in ("free_k_2to4", "fixed_k3"):
            r = pd.read_csv(ph / f"formation_reliability_game{g}_{variant}.csv")
            r.insert(0, "variant", variant)
            r.insert(0, "game", g)
            rel_rows.append(r)
    phys_lines = []
    for g in (1, 2):
        p = pd.read_csv(ph / f"physical_game{g}.csv")
        out = p[(~p["is_gk"]) & (p["minutes"] > 90)]
        phys_lines.append(
            f"- Game {g}: {len(out)} outfield players (both teams) played the full match; distance covered "
            f"{out['distance_m'].min():,.0f}-{out['distance_m'].max():,.0f} m, top speed up to "
            f"{p['top_speed_kmh'].max():.1f} km/h, up to {int(p['sprints'].max())} sprints.")
    return "\n".join([
        "#### Tracking data quality (Metrica sample games 1 and 2)\n",
        md_table(pd.DataFrame(rows)),
        "\n#### Physical output (smoothed speed, outfield players with a full match)\n",
        *phys_lines,
        "\n#### Formation detection reliability\n",
        "Share of 5-minute windows (per team and possession state) that produced the most "
        "common formation string. Low values mean the detected formation is unstable.\n",
        md_table(pd.concat(rel_rows, ignore_index=True)),
    ])


def video_section(res_dir) -> str:
    """Phase 7 tables, read from results/phase7 (empty string if that phase was not run)."""
    ph = res_dir / "phase7"
    if not (ph / "summary.json").exists():
        return ""
    s = json.loads((ph / "summary.json").read_text())
    shots = pd.read_csv(ph / "shots.csv")
    comp = pd.read_csv(ph / "tracker_comparison.csv")[
        ["tracker", "frames", "players_per_frame", "unique_track_ids", "mean_track_len_frames",
         "id_to_player_ratio", "ball_frames_share"]]
    qual = pd.read_csv(ph / "tracking_quality.csv")[
        ["segment", "start", "end", "players_per_frame", "unique_track_ids",
         "id_to_player_ratio", "ball_frames_share", "persons_removed_not_on_grass"]]
    motion = pd.read_csv(ph / "track_motion.csv")
    mw, fit, teams = s["mapped_window"], s["landmark_fit_residual_m"], s["team_counts_tracks"]
    lines = [
        "### Video results (optional Phase 7)\n",
        f"The clip has {s['video']['frames']} frames at {s['video']['fps']:.0f} fps "
        f"({s['video']['width']}x{s['video']['height']}). It was split into {s['shots_total']} "
        f"shots of at least 1 s; {s['shots_wide']} ({s['wide_seconds']:.1f} s) look like wide "
        "gameplay shots and were tracked, the rest (close-ups and other non-gameplay shots) "
        "were not analysed.\n",
        "#### Tracker comparison on the pitch-mapped shot (proxy metrics, not accuracy)\n",
        md_table(comp),
        f"\nChosen tracker: **{s['tracker_chosen']}** (lower `id_to_player_ratio`, i.e. less "
        "track fragmentation). A ratio of 1 would mean every player kept a single ID; the true "
        "number of ID switches cannot be measured without hand-labelled frames.\n",
        "#### Tracking proxies per tracked shot\n",
        md_table(qual),
        "\n#### Pitch mapping (one shot)\n",
        f"- Eight hand-picked landmarks, fit error {fit['mean']} m mean / {fit['max']} m max "
        "(this is how well the homography reproduces its own landmarks, **not** accuracy "
        "against the real pitch).",
        f"- Pitch mapping used on frames {mw['first_frame']}-{mw['last_frame']} "
        f"({mw['seconds']} s, {mw['share_of_shot']:.0%} of that shot). Frames count only if "
        f"the projected pitch lines sit on the painted lines (alignment score >= "
        f"{mw['min_alignment_threshold']}; {mw['alignment_at_reference']} at the reference frame).",
        f"- Shirt-colour teams over all tracked tracks: {teams.get('light', 0)} light-kit, "
        f"{teams.get('dark', 0)} dark-kit, {teams.get('other', 0)} other (referees, "
        "goalkeepers, ambiguous or too-short tracks).",
        f"- Speed/distance is only available for {len(motion)} tracks long enough to "
        f"estimate; {int(motion['implausible_speed'].sum())} of them has a peak speed above "
        "12 m/s and is flagged as implausible. Treat all values as unvalidated.\n",
        md_table(motion),
    ]
    return "\n".join(lines)


def build() -> str:
    res = resolve(load_config()["paths"]["results"])
    ds_text, ds = dataset_section(res)
    xg_text, xg = xg_section(res)
    sections = [START, "### Dataset\n\n" + ds_text, "### xG model results\n\n" + xg_text,
                "### Tracking results\n\n" + tracking_section(res)]
    video = video_section(res)
    if video:
        sections.append(video)
    block = "\n\n".join(sections + [END])
    (res / "summary.json").write_text(json.dumps({"dataset": ds, "xg": xg}, indent=2, default=str),
                                      encoding="utf-8")
    (res / "README_results_block.md").write_text(block, encoding="utf-8")
    return block


def splice(block: str) -> None:
    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(START.split(" (")[0]) + r".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit("README.md has no RESULTS markers; add them first")
    readme.write_text(pattern.sub(lambda _: block, text), encoding="utf-8")


if __name__ == "__main__":
    splice(build())
    print("README results block updated; see results/summary.json")
